# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - elite-prod-web-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://eliteprodacr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_5720faea442a42259281e8ed2446df91 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_39545dee7c584feabbe73b6f0f6f4599 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: eliteprodacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5720faea442a42259281e8ed2446df91 }}/nextjs-app:${{ github.sha }}
        file: ./Dockerfile
        no-cache: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'elite-prod-web-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6cfb2a0709734b099bfcd9d033b31d2c }}
        images: 'eliteprodacr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_5720faea442a42259281e8ed2446df91 }}/nextjs-app:${{ github.sha }}'